# Generated by Django 6.0.7 on 2026-08-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
    ]
