# Generated by Django 6.0.7 on 2026-08-06 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_phone_user_phone_number_remove_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="emergency_phone",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in format 09xxxxxxxxx",
                        regex="^09\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in format 09xxxxxxxxx",
                        regex="^09\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("teacher", "Teacher"),
                    ("education", "Education Officer"),
                    ("finance", "Finance Officer"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
