# Generated by Django 6.0.7 on 2026-08-26 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_classroom_name'),
        ('finance', '0002_alter_salary_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='salary_month_between_1_and_12'),
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='salary_amount_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='salaryrate',
            constraint=models.CheckConstraint(condition=models.Q(('base_rate__gt', 0)), name='salary_rate_greater_than_zero'),
        ),
    ]
