# Generated by Django 6.0.7 on 2026-08-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherassignment",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
