# Generated by Django 6.0.7 on 2026-08-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_alter_teacherassignment_end_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="term",
            old_name="end",
            new_name="start_date",
        ),
        migrations.RemoveField(
            model_name="term",
            name="start",
        ),
        migrations.AddField(
            model_name="term",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
