# Generated by Django 6.0.7 on 2026-08-14 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_rename_end_term_start_date_remove_term_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherassignment',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 12, 31)),
            preserve_default=False,
        ),
    ]
