# Generated by Django 6.0.7 on 2026-08-14 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_teacherassignment_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 12, 31)),
            preserve_default=False,
        ),
    ]
