# Generated by Django 6.0.7 on 2026-08-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_teacherassignment_end_date_alter_term_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='Python & Django - Class A', max_length=100),
            preserve_default=False,
        ),
    ]
