# Generated by Django 6.0.7 on 2026-08-15 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionreport',
            old_name='rejection_reson',
            new_name='rejection_reason',
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='session_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='submitted_at',
            field=models.DateTimeField(),
        ),
    ]
