# Generated by Django 6.0.7 on 2026-08-22 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_classroom_name'),
        ('reports', '0003_sessionreportstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sessionreport',
            constraint=models.UniqueConstraint(fields=('teacher', 'classroom', 'session_date'), name='unique_teacher_classroom_session_report'),
        ),
    ]
